# Generated by Django 5.2.4 on 2025-10-28 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='species',
            new_name='breed',
        ),
    ]
